pod logs updated

diff --git a/bwai-manifests.yaml b/bwai-manifests.yaml
--- a/bwai-manifests.yaml
+++ b/bwai-manifests.yaml
@@ -56,6 +56,7 @@ spec:
       containers:
       - name: busybox
         image: busybox:<INVALID_TAG>
+        command: ["/bin/sh", "-c", "echo 'bwai-server: Error: Too many unresolved situations... Restarting.' && exit 1"]
 
 # Staging
 ---
@@ -73,7 +74,7 @@ spec:
   containers:
   - name: bad-image
     image: busybox:badtag  # Invalid tag
-    command: ["sleep", "3600"]
+    command: ["/bin/sh", "-c", "echo '💔 Failed to download spinach... or love.' && sleep 3600"]
 
 ---
 apiVersion: apps/v1
@@ -94,7 +95,15 @@ spec:
       containers:
       - name: crash
         image: busybox
-        command: ["/bin/sh", "-c", "exit 1"]  # Crash immediately
+        command: 
+          - /bin/sh
+          - -c
+          - |
+            echo '💚 Salads leaves Consumed: 3 leaves';
+            echo '💔 Girls Messaged: 5';
+            echo '😵‍💫 Crashes: 3';
+            echo '🤖 Suresh: System Overwhelmed by Emotions. Exiting...';
+            exit 1
 
 ---
 apiVersion: v1
@@ -106,4 +115,10 @@ spec:
   containers:
   - name: no-cmd
     image: busybox:latest
+    command:
+      - /bin/sh
+      - -c
+      - |
+        echo "🤔 Pod waiting for Suresh to reply to all 5 girls...";
+        exit 1
     # No command or args, can potentially fail if image has no default CMD
